name: US-Quant-Auto-Scanner

on:
  schedule:
    # 한국 시간(KST) 기준 월요일 아침 7:23 ~ 토요일 아침 7:23
    # UTC 기준 일요일(0) 22:23 ~ 금요일(5) 22:23
    - cron: '23 22 * * 0-5'
    
  workflow_dispatch: # 필요할 때 언제든 버튼 눌러서 수동 실행 가능

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Libs
        run: pip install yfinance pandas pandas_ta requests lxml
      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
